In [1]:
def return_unique(l):

 res= []

 for i in l:
    if i not in res:
        res.append(i)
 return res
l=(1,2,2,2,3,3,4,5,5,6,6)
return_unique(l)

[1, 2, 3, 4, 5, 6]

In [1]:
def sort_sequence(s):
  temp = []

  for i in sorted(s.split('-')):
    temp.append(i)

  return "-".join(temp)

s = 'green-red-yellow-black-white'
sort_sequence(s)

'black-green-red-white-yellow'

In [ ]:
Sample List : [1, 2, 3, 4, 5, 6, 7, 8, 9]
Expected Result : [2, 4, 6, 8]

In [2]:
def is_even(l):
    temp=[]

    for i in l:
        if i%2==0:
            temp.append(i)

    return (temp)

is_even([1,2,3,4,5,6,7,8,9])

[2, 4, 6, 8]

In [1]:
L1 = [1,2,3]
L2 = [4,5,6]
L3 = [7,8,9]

list(map(lambda x,y,z:x+y+z,L1,L2,L3))



[12, 15, 18]

In [5]:
str1="FIFA world cup in 2022 will take place in Qatar"

list(filter(lambda x:True if x.lower()in "aieou" else False, str1))

['I', 'A', 'o', 'u', 'i', 'i', 'a', 'e', 'a', 'e', 'i', 'a', 'a']

In [13]:
employees = [
    {
        'fname':'Nitish',
        'lname':'Singh',
        'age' : 33,
        'grade':'skilled'
    },
    {
        'fname':'Ankit',
        'lname':'Verma',
        'age' : 34,
        'grade':'semi-skilled'
    },
    {
        'fname':'Neha',
        'lname':'Singh',
        'age' : 35,
        'grade':'highly-skilled'
    },
    {
        'fname':'Anurag',
        'lname':'Kumar',
        'age' : 30,
        'grade':'skilled'
    },
    {
        'fname':'Abhinav',
        'lname':'Sharma',
        'age' : 37,
        'grade':'highly-skilled'
    }
    
]

list(map(lambda x:x['fname']+' '+x['lname'], list(filter(lambda x:True if x ['grade']=='highly skilled' else False, employees))))

[]

In [2]:
import numpy as np

a=np.nan*np.empty(10)

a[4]=1
a


array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

In [6]:
a,b=map(int,input("enter the number: ").split())
x=np.random.random((a,b))
print( x)
print(x.mean())

enter the number:  2 5


[[0.77517668 0.83340938 0.11228597 0.32476611 0.72382457]
 [0.0933481  0.96869134 0.72924348 0.66352286 0.88913169]]
0.6113400180815971


In [7]:
def array(a,b):

    x=np.ones((a,b))

    x[1:-1, 1:-1]=0

    return x

array(4,5)    
    

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [18]:
import numpy as np

np.identity(6)



array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [20]:
m=np.zeros((5,5))
m+=np.arange(5)
m

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [4]:
import numpy as np

p= np.zeros((5,5))
p+= np.arange(5)
p


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [6]:
a= input().strip().split()
np.array(a[::-1],dtype=np.float32)

 2 3 5 7 8 


array([8., 7., 5., 3., 2.], dtype=float32)

In [11]:


a = np.zeros((2,3))
a.size

6

In [6]:
import numpy as np

m=[10,29,38,76,98,44]
n=np.array(m)

print(type(n))
print(n.ndim)
print(n.size)
print(n.shape)
print(n.dtype)

<class 'numpy.ndarray'>
1
6
(6,)
int64


In [8]:
n=np.arange(2,20,3)

print(n.shape)
print(n)

(6,)
[ 2  5  8 11 14 17]


In [15]:
m=np.arange(12)
print(m)
m[3]

[ 0  1  2  3  4  5  6  7  8  9 10 11]


np.int64(3)